// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	Categoryid   string `json:"categoryid"`
	Categoryname string `json:"categoryname"`
}

type Location struct {
	Locationid   string `json:"locationid"`
	Locationname string `json:"locationname"`
}

type NewLocation struct {
	Locationname string `json:"locationname"`
}

type NewUser struct {
	Useremail      string `json:"useremail"`
	Username       string `json:"username"`
	Profileimgaddr string `json:"profileimgaddr"`
}

type Premiumtype struct {
	Premiumid   string `json:"premiumid"`
	Premiumname string `json:"premiumname"`
}

type Privacy struct {
	Privacyid   string `json:"privacyid"`
	Privacyname string `json:"privacyname"`
}

type Restriction struct {
	Restrictionid       string `json:"restrictionid"`
	Restrictioncategory string `json:"restrictioncategory"`
}

type Tag struct {
	Tagid   string `json:"tagid"`
	Tagname string `json:"tagname"`
}

type Videotype struct {
	Videotypeid string `json:"videotypeid"`
	Videotype   string `json:"videotype"`
}
